#baseURL = "https://inspiring-brown-0a1d4c.netlify.com/"
baseURL = "https://aitoraznar.com/"
languageCode = "es-es"
title = "Aitor Aznar"
theme = "uilite"
googleAnalytics = "UA-44570722-1"
[permalinks]
  posts = "/blog"